name: Run tests

on:
  schedule:
     - cron: '0 0 * * *'  # Запуск в 00:00 каждый день
jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: "Использование main репозитория"
        uses: actions/checkout@v3
      - name: "Запуск тестов"
        run: mvn test
        continue-on-error: true
      - name: "Генерация аллюр"
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: target/allure-report
          allure_history: target/allure-history

      - name: "Создание ветки "
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: target/allure-history




