name: Maven Test for master1 branch

on:
 push:
 branches:
 - master1
 pull_request:
 branches:
 - master1

jobs:
 build:
 runs-on: ubuntu-latest

 steps:
 - name: Checkout code
 uses: actions/checkout@v3

 - name: Setup Java 11
 uses: actions/setup-java@v3
 with:
 java-version: '11'

 - name: Build and run tests with Maven
 run: mvn -B clean test

 - name: Collect test results
 run: |
 find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp '{}' /tmp/test-results/ \;

 - name: Upload test results
 uses: actions/upload-artifact@v3
 with:
 name: test-results
 path: /tmp/test-results/
