name: CI/CD for Java Project with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: yourusername/homework4restdocker:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Run tests in Docker container
        run: |
          docker run yourusername/homework4restdocker:latest mvn test

      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports/

      - name: Clean up Docker image
        if: always()
        run: |
          docker image prune -f

      - name: Docker logout
        if: always()
        run: |
          docker logout

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-results
          path: target/site/jacoco/

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify failure
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" --data '{
            "text": "Build failed for commit <${{ github.sha }}>. Please check details."
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify success
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" --data '{
            "text": "Build succeeded for commit <${{ github.sha }}>. Congrats!"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
