name: Maven Test for master1 branch

on:
  push:
    branches:
      - master1
  pull_request:
    branches:
      - master1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Compose
        uses: docker/setup-compose@v2

      - name: Build and run tests with Docker Compose
        run: |
          docker-compose up --build -d
          docker-compose run maven-test

      - name: Collect test results
        run: |
          docker-compose logs maven-test
          docker-compose down

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/
